# Generated by Django 4.2 on 2025-03-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='next_refill_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.TextField(default='have a good day'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('Not Sent', 'Not Sent'), ('Sent', 'Sent')], default='Not Sent', max_length=20),
        ),
    ]
