# Generated by Django 4.2 on 2025-03-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_amount',
            field=models.IntegerField(default=0),
        ),
    ]
